// AUTO-GENERATED from WPT html/dom/elements-*.js reflection definitions.
// (tag, idlName, contentAttr, ReflectKind) for str/bool/long/ulong/double/enum.
#[rustfmt::skip]
const ELEMENT_REFLECT_ATTRS: &[(&str, &str, &str, ReflectKind)] = &[
    ("div", "ariaAtomic", "aria-atomic", ReflectKind::Enum(&["true", "false"], "", "false")),
    ("div", "ariaAutoComplete", "aria-autocomplete", ReflectKind::Enum(&["inline", "list", "both", "none"], "none", "none")),
    ("div", "ariaBusy", "aria-busy", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaChecked", "aria-checked", ReflectKind::Enum(&["true", "false", "mixed"], "", "")),
    ("div", "ariaCurrent", "aria-current", ReflectKind::Enum(&["page", "step", "location", "date", "time", "true", "false"], "false", "true")),
    ("div", "ariaDisabled", "aria-disabled", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaExpanded", "aria-expanded", ReflectKind::Enum(&["true", "false"], "", "")),
    ("div", "ariaHasPopup", "aria-haspopup", ReflectKind::Enum(&["true", "false", "menu", "dialog", "listbox", "tree", "grid"], "", "false")),
    ("div", "ariaHidden", "aria-hidden", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaInvalid", "aria-invalid", ReflectKind::Enum(&["true", "false", "spelling", "grammar"], "false", "true")),
    ("div", "ariaLive", "aria-live", ReflectKind::Enum(&["polite", "assertive", "off"], "off", "off")),
    ("div", "ariaModal", "aria-modal", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaMultiLine", "aria-multiline", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaMultiSelectable", "aria-multiselectable", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaOrientation", "aria-orientation", ReflectKind::Enum(&["horizontal", "vertical"], "", "")),
    ("div", "ariaPressed", "aria-pressed", ReflectKind::Enum(&["true", "false", "mixed"], "", "")),
    ("div", "ariaReadOnly", "aria-readonly", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaRequired", "aria-required", ReflectKind::Enum(&["true", "false"], "false", "false")),
    ("div", "ariaSelected", "aria-selected", ReflectKind::Enum(&["true", "false"], "", "")),
    ("div", "ariaSort", "aria-sort", ReflectKind::Enum(&["ascending", "descending", "other", "none"], "none", "none")),
    ("img", "alt", "alt", ReflectKind::Str),
    ("img", "srcset", "srcset", ReflectKind::Str),
    ("img", "useMap", "usemap", ReflectKind::Str),
    ("img", "isMap", "ismap", ReflectKind::Bool),
    ("img", "type", "type", ReflectKind::ULong),
    ("img", "name", "name", ReflectKind::Str),
    ("img", "align", "align", ReflectKind::Str),
    ("img", "hspace", "hspace", ReflectKind::ULong),
    ("img", "vspace", "vspace", ReflectKind::ULong),
    ("img", "crossOrigin", "crossorigin", ReflectKind::Enum(&["anonymous", "use-credentials"], "", "anonymous")),
    ("img", "width", "width", ReflectKind::ULong),
    ("img", "height", "height", ReflectKind::ULong),
    ("img", "referrerPolicy", "referrerpolicy", ReflectKind::Enum(&["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], "", "")),
    ("img", "decoding", "decoding", ReflectKind::Enum(&["async", "sync", "auto"], "auto", "auto")),
    ("img", "border", "border", ReflectKind::Str),
    ("iframe", "srcdoc", "srcdoc", ReflectKind::Str),
    ("iframe", "name", "name", ReflectKind::Str),
    ("iframe", "allowFullscreen", "allowfullscreen", ReflectKind::Bool),
    ("iframe", "width", "width", ReflectKind::Str),
    ("iframe", "height", "height", ReflectKind::Str),
    ("iframe", "align", "align", ReflectKind::Str),
    ("iframe", "scrolling", "scrolling", ReflectKind::Str),
    ("iframe", "frameBorder", "frameborder", ReflectKind::Str),
    ("iframe", "type", "type", ReflectKind::Str),
    ("iframe", "referrerPolicy", "referrerpolicy", ReflectKind::Enum(&["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], "", "")),
    ("iframe", "marginHeight", "marginheight", ReflectKind::Str),
    ("iframe", "marginWidth", "marginwidth", ReflectKind::Str),
    ("embed", "type", "type", ReflectKind::Str),
    ("embed", "width", "width", ReflectKind::Str),
    ("embed", "height", "height", ReflectKind::Str),
    ("embed", "align", "align", ReflectKind::Str),
    ("embed", "name", "name", ReflectKind::Str),
    ("object", "type", "type", ReflectKind::Str),
    ("object", "name", "name", ReflectKind::Str),
    ("object", "useMap", "usemap", ReflectKind::Str),
    ("object", "width", "width", ReflectKind::Str),
    ("object", "height", "height", ReflectKind::Str),
    ("object", "align", "align", ReflectKind::Str),
    ("object", "archive", "archive", ReflectKind::Str),
    ("object", "code", "code", ReflectKind::Str),
    ("object", "declare", "declare", ReflectKind::Bool),
    ("object", "hspace", "hspace", ReflectKind::ULong),
    ("object", "standby", "standby", ReflectKind::Str),
    ("object", "vspace", "vspace", ReflectKind::ULong),
    ("object", "codeType", "codetype", ReflectKind::Str),
    ("object", "border", "border", ReflectKind::Str),
    ("param", "name", "name", ReflectKind::Str),
    ("param", "value", "value", ReflectKind::Str),
    ("param", "type", "type", ReflectKind::Str),
    ("param", "valueType", "valuetype", ReflectKind::Str),
    ("video", "autoplay", "autoplay", ReflectKind::Bool),
    ("video", "loop", "loop", ReflectKind::Bool),
    ("video", "controls", "controls", ReflectKind::Bool),
    ("video", "type", "type", ReflectKind::Bool),
    ("video", "width", "width", ReflectKind::ULong),
    ("video", "height", "height", ReflectKind::ULong),
    ("video", "playsInline", "playsinline", ReflectKind::Bool),
    ("video", "crossOrigin", "crossorigin", ReflectKind::Enum(&["anonymous", "use-credentials"], "", "anonymous")),
    ("video", "preload", "preload", ReflectKind::Enum(&["none", "metadata", "auto"], "", "")),
    ("video", "defaultMuted", "muted", ReflectKind::Bool),
    ("video", "loading", "loading", ReflectKind::Enum(&["lazy", "eager"], "eager", "eager")),
    ("audio", "autoplay", "autoplay", ReflectKind::Bool),
    ("audio", "loop", "loop", ReflectKind::Bool),
    ("audio", "controls", "controls", ReflectKind::Bool),
    ("audio", "type", "type", ReflectKind::Bool),
    ("audio", "crossOrigin", "crossorigin", ReflectKind::Enum(&["anonymous", "use-credentials"], "", "anonymous")),
    ("audio", "preload", "preload", ReflectKind::Enum(&["none", "metadata", "auto"], "", "")),
    ("audio", "defaultMuted", "muted", ReflectKind::Bool),
    ("audio", "loading", "loading", ReflectKind::Enum(&["lazy", "eager"], "eager", "eager")),
    ("source", "type", "type", ReflectKind::Str),
    ("source", "srcset", "srcset", ReflectKind::Str),
    ("source", "sizes", "sizes", ReflectKind::Str),
    ("source", "media", "media", ReflectKind::Str),
    ("track", "srclang", "srclang", ReflectKind::Str),
    ("track", "label", "label", ReflectKind::Str),
    ("track", "kind", "kind", ReflectKind::Enum(&["subtitles", "captions", "descriptions", "chapters", "metadata"], "subtitles", "metadata")),
    ("canvas", "type", "type", ReflectKind::ULong),
    ("canvas", "width", "width", ReflectKind::ULong),
    ("canvas", "height", "height", ReflectKind::ULong),
    ("map", "name", "name", ReflectKind::Str),
    ("area", "alt", "alt", ReflectKind::Str),
    ("area", "coords", "coords", ReflectKind::Str),
    ("area", "shape", "shape", ReflectKind::Str),
    ("area", "target", "target", ReflectKind::Str),
    ("area", "download", "download", ReflectKind::Str),
    ("area", "ping", "ping", ReflectKind::Str),
    ("area", "rel", "rel", ReflectKind::Str),
    ("area", "hreflang", "hreflang", ReflectKind::Str),
    ("area", "type", "type", ReflectKind::Str),
    ("area", "noHref", "nohref", ReflectKind::Bool),
    ("area", "referrerPolicy", "referrerpolicy", ReflectKind::Enum(&["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], "", "")),
    ("input", "accept", "accept", ReflectKind::Str),
    ("input", "alt", "alt", ReflectKind::Str),
    ("input", "type", "type", ReflectKind::Str),
    ("input", "dirName", "dirname", ReflectKind::Str),
    ("input", "disabled", "disabled", ReflectKind::Bool),
    ("input", "formNoValidate", "formnovalidate", ReflectKind::Bool),
    ("input", "formTarget", "formtarget", ReflectKind::Str),
    ("input", "max", "max", ReflectKind::Str),
    ("input", "min", "min", ReflectKind::Str),
    ("input", "multiple", "multiple", ReflectKind::Bool),
    ("input", "name", "name", ReflectKind::Str),
    ("input", "pattern", "pattern", ReflectKind::Str),
    ("input", "placeholder", "placeholder", ReflectKind::Str),
    ("input", "readOnly", "readonly", ReflectKind::Bool),
    ("input", "required", "required", ReflectKind::Bool),
    ("input", "step", "step", ReflectKind::Str),
    ("input", "align", "align", ReflectKind::Str),
    ("input", "useMap", "usemap", ReflectKind::Str),
    ("input", "autocomplete", "autocomplete", ReflectKind::Str),
    ("input", "defaultChecked", "checked", ReflectKind::Bool),
    ("input", "formEnctype", "formenctype", ReflectKind::Enum(&["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], "", "application/x-www-form-urlencoded")),
    ("input", "formMethod", "formmethod", ReflectKind::Enum(&["get", "post"], "", "get")),
    ("input", "height", "height", ReflectKind::ULong),
    ("input", "size", "size", ReflectKind::ULong),
    ("input", "width", "width", ReflectKind::ULong),
    ("input", "defaultValue", "value", ReflectKind::Str),
    ("form", "type", "type", ReflectKind::Str),
    ("form", "name", "name", ReflectKind::Str),
    ("form", "noValidate", "novalidate", ReflectKind::Bool),
    ("form", "target", "target", ReflectKind::Str),
    ("form", "acceptCharset", "accept-charset", ReflectKind::Str),
    ("form", "autocomplete", "autocomplete", ReflectKind::Enum(&["on", "off"], "on", "on")),
    ("form", "enctype", "enctype", ReflectKind::Enum(&["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], "application/x-www-form-urlencoded", "application/x-www-form-urlencoded")),
    ("form", "encoding", "enctype", ReflectKind::Enum(&["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], "application/x-www-form-urlencoded", "application/x-www-form-urlencoded")),
    ("form", "method", "method", ReflectKind::Enum(&["get", "post", "dialog"], "get", "get")),
    ("fieldset", "disabled", "disabled", ReflectKind::Bool),
    ("fieldset", "name", "name", ReflectKind::Str),
    ("legend", "align", "align", ReflectKind::Str),
    ("label", "type", "type", ReflectKind::Str),
    ("label", "htmlFor", "for", ReflectKind::Str),
    ("button", "disabled", "disabled", ReflectKind::Bool),
    ("button", "formNoValidate", "formnovalidate", ReflectKind::Bool),
    ("button", "formTarget", "formtarget", ReflectKind::Str),
    ("button", "name", "name", ReflectKind::Str),
    ("button", "value", "value", ReflectKind::Str),
    ("button", "formEnctype", "formenctype", ReflectKind::Enum(&["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], "", "application/x-www-form-urlencoded")),
    ("button", "formMethod", "formmethod", ReflectKind::Enum(&["get", "post", "dialog"], "", "get")),
    ("button", "type", "type", ReflectKind::Enum(&["submit", "reset", "button"], "submit", "submit")),
    ("select", "type", "type", ReflectKind::Str),
    ("select", "disabled", "disabled", ReflectKind::Bool),
    ("select", "multiple", "multiple", ReflectKind::Bool),
    ("select", "name", "name", ReflectKind::Str),
    ("select", "required", "required", ReflectKind::Bool),
    ("select", "autocomplete", "autocomplete", ReflectKind::Str),
    ("select", "size", "size", ReflectKind::ULong),
    ("optgroup", "disabled", "disabled", ReflectKind::Bool),
    ("optgroup", "label", "label", ReflectKind::Str),
    ("option", "disabled", "disabled", ReflectKind::Bool),
    ("option", "type", "type", ReflectKind::Str),
    ("option", "label", "label", ReflectKind::Str),
    ("option", "defaultSelected", "selected", ReflectKind::Bool),
    ("option", "value", "value", ReflectKind::Str),
    ("textarea", "type", "type", ReflectKind::Str),
    ("textarea", "dirName", "dirname", ReflectKind::Str),
    ("textarea", "disabled", "disabled", ReflectKind::Bool),
    ("textarea", "name", "name", ReflectKind::Str),
    ("textarea", "placeholder", "placeholder", ReflectKind::Str),
    ("textarea", "readOnly", "readonly", ReflectKind::Bool),
    ("textarea", "required", "required", ReflectKind::Bool),
    ("textarea", "wrap", "wrap", ReflectKind::Str),
    ("textarea", "autocomplete", "autocomplete", ReflectKind::Str),
    ("textarea", "cols", "cols", ReflectKind::ULong),
    ("textarea", "rows", "rows", ReflectKind::ULong),
    ("output", "name", "name", ReflectKind::Str),
    ("progress", "type", "type", ReflectKind::Double),
    ("progress", "max", "max", ReflectKind::Double),
    ("meter", "type", "type", ReflectKind::Double),
    ("meter", "value", "value", ReflectKind::Double),
    ("meter", "min", "min", ReflectKind::Double),
    ("meter", "max", "max", ReflectKind::Double),
    ("meter", "low", "low", ReflectKind::Double),
    ("meter", "high", "high", ReflectKind::Double),
    ("meter", "optimum", "optimum", ReflectKind::Double),
    ("p", "align", "align", ReflectKind::Str),
    ("hr", "align", "align", ReflectKind::Str),
    ("hr", "color", "color", ReflectKind::Str),
    ("hr", "noShade", "noshade", ReflectKind::Bool),
    ("hr", "size", "size", ReflectKind::Str),
    ("hr", "width", "width", ReflectKind::Str),
    ("pre", "width", "width", ReflectKind::Long),
    ("ol", "reversed", "reversed", ReflectKind::Bool),
    ("ol", "type", "type", ReflectKind::Long),
    ("ol", "compact", "compact", ReflectKind::Bool),
    ("ol", "start", "start", ReflectKind::Long),
    ("ul", "compact", "compact", ReflectKind::Bool),
    ("ul", "type", "type", ReflectKind::Str),
    ("li", "value", "value", ReflectKind::Long),
    ("li", "type", "type", ReflectKind::Str),
    ("dl", "compact", "compact", ReflectKind::Bool),
    ("div", "align", "align", ReflectKind::Str),
    ("base", "target", "target", ReflectKind::Str),
    ("link", "rel", "rel", ReflectKind::Str),
    ("link", "media", "media", ReflectKind::Str),
    ("link", "nonce", "nonce", ReflectKind::Str),
    ("link", "integrity", "integrity", ReflectKind::Str),
    ("link", "hreflang", "hreflang", ReflectKind::Str),
    ("link", "type", "type", ReflectKind::Str),
    ("link", "charset", "charset", ReflectKind::Str),
    ("link", "rev", "rev", ReflectKind::Str),
    ("link", "target", "target", ReflectKind::Str),
    ("link", "crossOrigin", "crossorigin", ReflectKind::Enum(&["anonymous", "use-credentials"], "", "anonymous")),
    ("link", "as", "as", ReflectKind::Enum(&["fetch", "audio", "document", "embed", "font", "image", "manifest", "object", "report", "script", "sharedworker", "style", "track", "video", "worker", "xslt"], "", "")),
    ("link", "referrerPolicy", "referrerpolicy", ReflectKind::Enum(&["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], "", "")),
    ("meta", "name", "name", ReflectKind::Str),
    ("meta", "type", "type", ReflectKind::Str),
    ("meta", "content", "content", ReflectKind::Str),
    ("meta", "media", "media", ReflectKind::Str),
    ("meta", "scheme", "scheme", ReflectKind::Str),
    ("meta", "httpEquiv", "http-equiv", ReflectKind::Str),
    ("style", "media", "media", ReflectKind::Str),
    ("style", "nonce", "nonce", ReflectKind::Str),
    ("style", "type", "type", ReflectKind::Str),
    ("html", "version", "version", ReflectKind::Str),
    ("script", "type", "type", ReflectKind::Str),
    ("script", "noModule", "nomodule", ReflectKind::Bool),
    ("script", "charset", "charset", ReflectKind::Str),
    ("script", "defer", "defer", ReflectKind::Bool),
    ("script", "integrity", "integrity", ReflectKind::Str),
    ("script", "event", "event", ReflectKind::Str),
    ("script", "crossOrigin", "crossorigin", ReflectKind::Enum(&["anonymous", "use-credentials"], "", "anonymous")),
    ("script", "htmlFor", "for", ReflectKind::Str),
    ("slot", "name", "name", ReflectKind::Str),
    ("ins", "dateTime", "datetime", ReflectKind::Str),
    ("del", "dateTime", "datetime", ReflectKind::Str),
    ("details", "open", "open", ReflectKind::Bool),
    ("menu", "compact", "compact", ReflectKind::Bool),
    ("dialog", "open", "open", ReflectKind::Bool),
    ("undefinedelement", "enterKeyHint", "enterkeyhint", ReflectKind::Enum(&["enter", "done", "go", "next", "previous", "search", "send"], "", "")),
    ("undefinedelement", "inputMode", "inputmode", ReflectKind::Enum(&["none", "text", "tel", "url", "email", "numeric", "decimal", "search"], "", "")),
    ("marquee", "bgColor", "bgcolor", ReflectKind::Str),
    ("marquee", "height", "height", ReflectKind::Str),
    ("marquee", "hspace", "hspace", ReflectKind::ULong),
    ("marquee", "type", "type", ReflectKind::ULong),
    ("marquee", "trueSpeed", "truespeed", ReflectKind::Bool),
    ("marquee", "vspace", "vspace", ReflectKind::ULong),
    ("marquee", "width", "width", ReflectKind::Str),
    ("marquee", "behavior", "behavior", ReflectKind::Enum(&["scroll", "slide", "alternate"], "scroll", "scroll")),
    ("marquee", "direction", "direction", ReflectKind::Enum(&["up", "right", "down", "left"], "left", "left")),
    ("marquee", "scrollAmount", "scrollamount", ReflectKind::ULong),
    ("marquee", "scrollDelay", "scrolldelay", ReflectKind::ULong),
    ("frameset", "cols", "cols", ReflectKind::Str),
    ("frameset", "rows", "rows", ReflectKind::Str),
    ("frame", "name", "name", ReflectKind::Str),
    ("frame", "scrolling", "scrolling", ReflectKind::Str),
    ("frame", "frameBorder", "frameborder", ReflectKind::Str),
    ("frame", "noResize", "noresize", ReflectKind::Bool),
    ("frame", "type", "type", ReflectKind::Str),
    ("frame", "marginHeight", "marginheight", ReflectKind::Str),
    ("frame", "marginWidth", "marginwidth", ReflectKind::Str),
    ("dir", "compact", "compact", ReflectKind::Bool),
    ("font", "type", "type", ReflectKind::Str),
    ("font", "face", "face", ReflectKind::Str),
    ("font", "size", "size", ReflectKind::Str),
    ("font", "color", "color", ReflectKind::Str),
    ("body", "type", "type", ReflectKind::Str),
    ("body", "background", "background", ReflectKind::Str),
    ("body", "text", "text", ReflectKind::Str),
    ("body", "link", "link", ReflectKind::Str),
    ("body", "vLink", "vlink", ReflectKind::Str),
    ("body", "aLink", "alink", ReflectKind::Str),
    ("body", "bgColor", "bgcolor", ReflectKind::Str),
    ("h1", "align", "align", ReflectKind::Str),
    ("h2", "align", "align", ReflectKind::Str),
    ("h3", "align", "align", ReflectKind::Str),
    ("h4", "align", "align", ReflectKind::Str),
    ("h5", "align", "align", ReflectKind::Str),
    ("h6", "align", "align", ReflectKind::Str),
    ("table", "align", "align", ReflectKind::Str),
    ("table", "border", "border", ReflectKind::Str),
    ("table", "frame", "frame", ReflectKind::Str),
    ("table", "rules", "rules", ReflectKind::Str),
    ("table", "summary", "summary", ReflectKind::Str),
    ("table", "width", "width", ReflectKind::Str),
    ("table", "type", "type", ReflectKind::Str),
    ("table", "bgColor", "bgcolor", ReflectKind::Str),
    ("table", "cellPadding", "cellpadding", ReflectKind::Str),
    ("table", "cellSpacing", "cellspacing", ReflectKind::Str),
    ("caption", "align", "align", ReflectKind::Str),
    ("colgroup", "type", "type", ReflectKind::ULong),
    ("colgroup", "align", "align", ReflectKind::Str),
    ("colgroup", "vAlign", "valign", ReflectKind::Str),
    ("colgroup", "width", "width", ReflectKind::Str),
    ("colgroup", "span", "span", ReflectKind::ULong),
    ("colgroup", "ch", "char", ReflectKind::Str),
    ("colgroup", "chOff", "charoff", ReflectKind::Str),
    ("col", "type", "type", ReflectKind::ULong),
    ("col", "align", "align", ReflectKind::Str),
    ("col", "vAlign", "valign", ReflectKind::Str),
    ("col", "width", "width", ReflectKind::Str),
    ("col", "span", "span", ReflectKind::ULong),
    ("col", "ch", "char", ReflectKind::Str),
    ("col", "chOff", "charoff", ReflectKind::Str),
    ("tbody", "align", "align", ReflectKind::Str),
    ("tbody", "type", "type", ReflectKind::Str),
    ("tbody", "vAlign", "valign", ReflectKind::Str),
    ("tbody", "ch", "char", ReflectKind::Str),
    ("tbody", "chOff", "charoff", ReflectKind::Str),
    ("thead", "align", "align", ReflectKind::Str),
    ("thead", "type", "type", ReflectKind::Str),
    ("thead", "vAlign", "valign", ReflectKind::Str),
    ("thead", "ch", "char", ReflectKind::Str),
    ("thead", "chOff", "charoff", ReflectKind::Str),
    ("tfoot", "align", "align", ReflectKind::Str),
    ("tfoot", "type", "type", ReflectKind::Str),
    ("tfoot", "vAlign", "valign", ReflectKind::Str),
    ("tfoot", "ch", "char", ReflectKind::Str),
    ("tfoot", "chOff", "charoff", ReflectKind::Str),
    ("tr", "align", "align", ReflectKind::Str),
    ("tr", "type", "type", ReflectKind::Str),
    ("tr", "vAlign", "valign", ReflectKind::Str),
    ("tr", "ch", "char", ReflectKind::Str),
    ("tr", "chOff", "charoff", ReflectKind::Str),
    ("tr", "bgColor", "bgcolor", ReflectKind::Str),
    ("td", "type", "type", ReflectKind::ULong),
    ("td", "headers", "headers", ReflectKind::Str),
    ("td", "abbr", "abbr", ReflectKind::Str),
    ("td", "align", "align", ReflectKind::Str),
    ("td", "axis", "axis", ReflectKind::Str),
    ("td", "height", "height", ReflectKind::Str),
    ("td", "width", "width", ReflectKind::Str),
    ("td", "noWrap", "nowrap", ReflectKind::Bool),
    ("td", "vAlign", "valign", ReflectKind::Str),
    ("td", "colSpan", "colspan", ReflectKind::ULong),
    ("td", "rowSpan", "rowspan", ReflectKind::ULong),
    ("td", "scope", "scope", ReflectKind::Enum(&["row", "col", "rowgroup", "colgroup"], "", "")),
    ("td", "ch", "char", ReflectKind::Str),
    ("td", "chOff", "charoff", ReflectKind::Str),
    ("td", "bgColor", "bgcolor", ReflectKind::Str),
    ("th", "type", "type", ReflectKind::ULong),
    ("th", "headers", "headers", ReflectKind::Str),
    ("th", "abbr", "abbr", ReflectKind::Str),
    ("th", "align", "align", ReflectKind::Str),
    ("th", "axis", "axis", ReflectKind::Str),
    ("th", "height", "height", ReflectKind::Str),
    ("th", "width", "width", ReflectKind::Str),
    ("th", "noWrap", "nowrap", ReflectKind::Bool),
    ("th", "vAlign", "valign", ReflectKind::Str),
    ("th", "colSpan", "colspan", ReflectKind::ULong),
    ("th", "rowSpan", "rowspan", ReflectKind::ULong),
    ("th", "scope", "scope", ReflectKind::Enum(&["row", "col", "rowgroup", "colgroup"], "", "")),
    ("th", "ch", "char", ReflectKind::Str),
    ("th", "chOff", "charoff", ReflectKind::Str),
    ("th", "bgColor", "bgcolor", ReflectKind::Str),
    ("a", "target", "target", ReflectKind::Str),
    ("a", "download", "download", ReflectKind::Str),
    ("a", "ping", "ping", ReflectKind::Str),
    ("a", "rel", "rel", ReflectKind::Str),
    ("a", "hreflang", "hreflang", ReflectKind::Str),
    ("a", "type", "type", ReflectKind::Str),
    ("a", "coords", "coords", ReflectKind::Str),
    ("a", "charset", "charset", ReflectKind::Str),
    ("a", "name", "name", ReflectKind::Str),
    ("a", "rev", "rev", ReflectKind::Str),
    ("a", "shape", "shape", ReflectKind::Str),
    ("a", "referrerPolicy", "referrerpolicy", ReflectKind::Enum(&["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], "", "")),
    ("data", "value", "value", ReflectKind::Str),
    ("time", "dateTime", "datetime", ReflectKind::Str),
    ("br", "clear", "clear", ReflectKind::Str),
];
